cocktaildb:
  api-url: https://www.thecocktaildb.com/api/json/v1/1

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 3000
        loggerLevel: full
  hystrix:
    enabled: true